M48
; DRILL file {KiCad (6.0.10)} date Sun Mar  5 19:00:10 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-05T19:00:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.9065Y-2.3233
X4.0974Y-2.3233
T2
X3.8947Y-2.204
X4.1093Y-2.204
T0
M30
